const shipments = {
  // shipment6: {
  //   client: "Viña Santa Rita",
  //   poNumber: "5023-48K",
  //   product: "Truffle Risotto",
  //   steamshipLine: "ONE",
  //   supplier: "Gourmet Italian Imports",
  //   container: "SZLU9446927",
  //   eta: "2024-02-15",
  //   status: "In Transit",
  // },
  // shipment1: {
  //   client: "Viña Concha y Toro",
  //   steamshipLine: "MSC",
  //   poNumber: "5023-165K",
  //   product: "French Champagne",
  //   supplier: "Luxury European Wines",
  //   container: "CRSU6024460",
  //   eta: "2024-02-14",
  //   status: "In Transit",
  // },
  // shipment2: {
  //   client: "Empresas Carozzi",
  //   steamshipLine: "MSC",
  //   poNumber: "5023-162K",
  //   product: "Spanish Saffron",
  //   supplier: "Gourmet Europe",
  //   container: "GESU9357858",
  //   eta: "2024-02-14",
  //   status: "In Transit",
  // },

  // shipment3: {
  //   client: "Aconcagua Foods",
  //   steamshipLine: "Maersk",
  //   poNumber: "5023-161K",
  //   product: "Italian Olive Oil",
  //   supplier: "Premium Italian Imports",
  //   container: "SUDU6068809",
  //   eta: "2024-02-15",
  //   status: "In Transit",
  // },
  // shipment4: {
  //   client: "Viña Montes",
  //   poNumber: "5023-164K",
  //   product: "Swiss Chocolate",
  //   steamshipLine: "Maersk",
  //   supplier: "Luxury European Chocolates",
  //   container: "MWCU5295851",
  //   eta: "2024-02-15",
  //   status: "In Transit",
  // },
  shipment5: {
    client: "Comercial Siglo XXI",
    poNumber: "5023-147K",
    product: "Belgian Truffles",
    steamshipLine: "HAPAG",
    supplier: "Premium European Delights",
    container: "SEGU9097837",
    eta: "2024-02-15",
    status: "In Transit",
  },
};

module.exports = shipments;
