
const shipments = {
  shipment1: {
    client: "Viña Concha y Toro",
    steamshipLine: "MSC",
    poNumber: "5023-165K",
    product: "French Champagne",
    supplier: "Luxury European Wines",
    container: "CRSU6024460",
    eta: "2024-02-14",
    status: "In Transit",
  },
  shipment2: {
    client: "Empresas Carozzi",
    steamshipLine: "MSC",
    poNumber: "5023-162K",
    product: "Spanish Saffron",
    supplier: "Gourmet Europe",
    container: "GESU9357858",
    eta: "2024-02-14",
    status: "In Transit",
  },
  shipment3: {
    client: "Aconcagua Foods",
    steamshipLine: "Maersk",
    poNumber: "5023-161K",
    product: "Italian Olive Oil",
    supplier: "Premium Italian Imports",
    container: "SUDU6068809",
    eta: "2024-02-15",
    status: "In Transit",
  },
  shipment4: {
    client: "Viña Montes",
    poNumber: "5023-164K",
    product: "Swiss Chocolate",
    steamshipLine: "Maersk",
    supplier: "Luxury European Chocolates",
    container: "MWCU5295851",
    eta: "2024-02-15",
    status: "In Transit",
  },
  shipment5: {
    client: "Delicatessen Corp",
    steamshipLine: "MSC",
    poNumber: "5023-166K",
    product: "Italian Truffles",
    supplier: "Truffle World",
    container: "SZLU9200194",
    eta: "2024-02-16",
    status: "In Transit",
  },
  shipment6: {
    client: "Gourmet Emporium",
    steamshipLine: "Maersk",
    poNumber: "5023-167K",
    product: "Belgian Beer",
    supplier: "Authentic Belgian Brewery",
    container: "MNBU3749634",
    eta: "2024-02-16",
    status: "In Transit",
  },
  shipment7: {
    client: "Cuisine Creations",
    steamshipLine: "Maersk",
    poNumber: "5023-168K",
    product: "Portuguese Port Wine",
    supplier: "Port Wine Co.",
    container: "MWCU6828467",
    eta: "2024-02-17",
    status: "In Transit",
  },
  shipment8: {
    client: "Global Foods Inc.",
    steamshipLine: "Maersk",
    poNumber: "5023-169K",
    product: "Greek Feta Cheese",
    supplier: "Mediterranean Dairy Co.",
    container: "MNBU3187521",
    eta: "2024-02-17",
    status: "In Transit",
  },
};

module.exports = shipments;
